### ISSUE TITLE
PostgreSQL 19

### ISSUE THREAD

**Issue by wolfgangwalther** [supabase/pg_net#257]
Currently fails to build with PostgreSQL 19 beta 1 in https://github.com/NixOS/nixpkgs/pull/531301.

*Tail* of the log:

```
src/core.c:231:26: error: incompatible pointer types passing 'JsonbParseState **' (aka 'struct JsonbParseState **') to parameter of type 'JsonbInState *' (aka 'struct JsonbInState *') [-Werror,-Wincompatible-pointer-types]
  231 |     (void)pushJsonbValue(&headers, WJB_VALUE, &value);
      |                          ^~~~~~~~
/nix/store/g6543ym63fizn39ibhkfi87z3bhxvghx-postgresql-19beta1-dev/include/server/utils/jsonb.h:434:42: note: passing argument to parameter 'pstate' here
  434 | extern void pushJsonbValue(JsonbInState *pstate,
      |                                          ^
src/core.c:235:59: error: incompatible pointer types passing 'JsonbParseState **' (aka 'struct JsonbParseState **') to parameter of type 'JsonbInState *' (aka 'struct JsonbInState *') [-Werror,-Wincompatible-pointer-types]
  235 |   Jsonb *jsonb_headers = JsonbValueToJsonb(pushJsonbValue(&headers, WJB_END_OBJECT, NULL));
      |                                                           ^~~~~~~~
/nix/store/g6543ym63fizn39ibhkfi87z3bhxvghx-postgresql-19beta1-dev/include/server/utils/jsonb.h:434:42: note: passing argument to parameter 'pstate' here
  434 | extern void pushJsonbValue(JsonbInState *pstate,
      |                                          ^
src/core.c:235:44: error: passing 'void' to parameter of incompatible type 'JsonbValue *' (aka 'struct JsonbValue *')
  235 |   Jsonb *jsonb_headers = JsonbValueToJsonb(pushJsonbValue(&headers, WJB_END_OBJECT, NULL));
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/g6543ym63fizn39ibhkfi87z3bhxvghx-postgresql-19beta1-dev/include/server/utils/jsonb.h:440:45: note: passing argument to parameter 'val' here
  440 | extern Jsonb *JsonbValueToJsonb(JsonbValue *val);
      |                                             ^
6 errors generated.
make: *** [<builtin>: src/core.o] Error 1
```

**Comment by steve-chavez** [comment]
Fix released on https://github.com/supabase/pg_net/releases/tag/v0.20.5
